### ISSUE TITLE
Unable to compile on Fedora 42 (6.16.5-200.fc42.x86_64)

### ISSUE THREAD

**Issue by ilie-blureon** [Query-Doctor/stethoscope#1]
Tried to run go generate and got the following errors:
```
/home/admin/stethoscope/ebpf/bpf.c:108:29: warning: unused function 'is_non_standard_postgres_identifier' [-Wunused-function]
  108 | static __always_inline bool is_non_standard_postgres_identifier(__u32 next) {
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ilie/stethoscope/ebpf/bpf.c:52:17: error: Invalid usage of the XADD return value
   52 |   __u64 index = __sync_fetch_and_add(&stack->top, 1);
      |                 ^
/home/ilie/stethoscope/ebpf/bpf.c:52:17: error: Invalid usage of the XADD return value
/home/ilie/stethoscope/ebpf/bpf.c:52:17: error: Invalid usage of the XADD return value
/home/ilie/stethoscope/ebpf/bpf.c:52:17: error: Invalid usage of the XADD return value
1 warning and 4 errors generated.
Error: compile: exit status 1
exit status 1
userland.go:23: running "go": exit status 1
```

**Comment by Xetera** [comment]
Thanks for the report, looks like I did some of this work on a slightly outdated kernel (6.8.x) which doesn't have this problem. I'll look into upgrading later and see if I can find a fix
